chunking_presets:
  SMALL:
    chunk_size: 400
    chunk_overlap: 80
    separators: ["\n\n", "\n", ".", " "]
  MEDIUM:
    chunk_size: 1000
    chunk_overlap: 200
    separators: ["\n\n", "\n", ".", " "]
  LARGE:
    chunk_size: 2000
    chunk_overlap: 300
    separators: ["\n\n", "\n", ".", " "]