services:
  rag:
    build: .
    container_name: rag_progetto
    ports:
      - "8000:8000"
    volumes:
      - .:/app                      # Hot-reload del codice
      - ./documenti_da_indicizzare:/app/documenti_da_indicizzare # PDF
    environment:
      - OLLAMA_HOST_APP=http://ollama:11434
      - QDRANT_HOST_APP=http://qdrant:6333
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - qdrant
      - ollama

  # Database Vettoriale per i PDF
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant_db
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  # Motore LLM e Embedding
  ollama:
    image: ollama/ollama
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

# Configurazione Ollama per usare GPU NVIDIA scommentare se necessario
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  qdrant_data:
  ollama_data: